---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Snapshot Info
      community_fabric.ansible.snapshot_info:
        provider: "{{ provider }}"
        snapshot_id: 22fc2140-b1d2-433d-87d7-e26c67b52f1d
