---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Snapshot Info
      community_fabric.ansible.table_info:
        provider: "{{ provider }}"
        snapshot_id: 89c1c1b3-7a9f-4609-9f85-6e6265bd7d94
        technology: inventory
        table: devices
      register: devices

    - name: Loop over returned devices
      debug:
        msg: "{{ item.hostname }} vendor: {{ item.vendor }}"
      loop: "{{ devices.data }}"

    # - name: Find IP address of a MAC address
    #   community_fabric.ansible.table_info:
    #     provider: "{{ provider }}"
    #     snapshot_id: 89c1c1b3-7a9f-4609-9f85-6e6265bd7d94
    #     technology: addressing
    #     table: arp_table
    #     filter:
    #       mac:
    #         - like
    #         - 084f.a900.0029
    #     columns:
    #       - hostname
    #       - intName
    #       - ip
    #       - mac
    #   register: arp_result
    
    # - name: IP Belonging to MAC
    #   debug: 
    #     msg: "MAC: {{ item.mac }} has an IP of {{ item.ip }} on device {{ item.hostname }} ({{ item.intName }})"
    #   loop: "{{ arp_result.data }}"

    # - name: Filter and noncompliant NTP configurations
    #   community_fabric.ansible.table_info:
    #     provider: "{{ provider }}" 
    #     snapshot_id: 89c1c1b3-7a9f-4609-9f85-6e6265bd7d94
    #     technology: management
    #     table: ntp_summary
    #     filter: {sources: ["color", "eq", "30"]}
    #     report: /technology/management/ntp/summary
    #   register: ntp_summary

    # - name: IP Belonging to MAC
    #   debug: 
    #     msg: "Device {{ item.hostname }} is not compliant NTP is currently configured to {{ item.sources.data }}"
    #   loop: "{{ ntp_summary.data }}"
          
