---
- hosts: all
  connection: local
  become: False
  gather_facts: False

  vars: 
    ipf_token: xxx
    ipf_url: xxx

  tasks:
    - name: Filter and select columns on technology table
      ipfabric.ansible.table_info:
        provider:
          base_url: "{{ ipf_url }}"
          token: "{{ ipf_token }}"
          verify: false
        technology: management
        table: ntp_summary
        filter: {sources: ["color", "eq", "30"]}
        report: /technology/management/ntp/summary
      delegate_to: localhost
      run_once: true
      register: NTP_DATA
    
    - name: test
      debug:
        msg: "{{ inventory_hostname }} not compliant"
      loop: "{{ NTP_DATA.data }}"
      when: inventory_hostname == item.hostname

